---
name: WWW-Bebo
version: 0.02
author:
  - 'Grant Grueninger <grantg@cpan.org>'
abstract: Automate interaction with Bebo.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  WWW::Sitebase::Navigator: 0.03
build_requires:
  Test::More: 0
provides:
  WWW::Bebo:
    file: lib/WWW/Bebo.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
